// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreviewDeploy.Server.Data;

#nullable disable

namespace PreviewDeploy.Server.Migrations
{
    [DbContext(typeof(PreviewDeployDbContext))]
    partial class PreviewDeployDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PreviewDeploy.Server.Data.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Owner", "Repo")
                        .IsUnique();

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("PreviewDeploy.Server.Data.DeployEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("deploy_events", (string)null);
                });

            modelBuilder.Entity("PreviewDeploy.Server.Data.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("PreviewDeploy.Server.Data.DeployEvent", b =>
                {
                    b.HasOne("PreviewDeploy.Server.Data.App", "App")
                        .WithMany("Events")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("PreviewDeploy.Server.Data.Deployment", b =>
                {
                    b.HasOne("PreviewDeploy.Server.Data.App", "App")
                        .WithMany("Deployments")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("PreviewDeploy.Server.Data.App", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
